server:
  port: 8080

liquibase:
  change-log: classpath:db/changelog/changelog-main.xml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_development
    username: postgres
    password: password
scheduler:
  track-status:
    cron: "0 0 1 * * *"